on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - name: Show ref
        run: echo "Git branch ref:" ${{github.ref}}
      - if: github.ref == 'refs/heads/main'
        env:
          ABC: test_main
      - if: github.ref == 'refs/heads/develop'
        env:
          ABC: test_develop
      - name: Show ref
        run: echo "Git branch ref:" ${{ $ABC }}
      - name: Get provisioner
        run: go get github.com/ross-spencer/knock-knock
        shell: bash
      - name: Install provisioner
        run: go install $HOME/go/src/github.com/ross-spencer/knock-knock/
        shell: bash
      - name: Run provisioner
        run: $HOME/go/bin/knock-knock -life=2h -host=develop-RAND.itforarchivists.com -env=${{ secrets.SECRET_ONE }},${{ secrets.SECRET_TWO }},${{ secrets.SECRET_THREE }} $HOME/provisioner/scripts/develop.yaml
        shell: bash
