on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: ross-spencer/steeplechase@v3
        with:
          who-to-greet: 'Mona the Octocat'
          secret-one: ${{ secrets.SECRET_ONE }}
          secret-two: ${{ secrets.SECRET_TWO }}
          secret-three: ${{ secrets.SECRET_THREE }}
      - name: Show ref
        run: echo "Git branch ref:" ${{github.ref}}
      - name: Get provisioner
        run: go get github.com/ross-spencer/knock-knock
        shell: bash
      - name: Install provisioner
        run: go install $HOME/go/src/github.com/ross-spencer/knock-knock/
        shell: bash
      - name: Run provisioner
        run: $HOME/go/bin/knock-knock -life=2h -host=develop-RAND.itforarchivists.com -env=${{ secrets.SECRET_ONE }},${{ secrets.SECRET_TWO }},${{ secrets.SECRET_THREE }} $HOME/provisioner/scripts/develop.yaml
        shell: bash
